### ISSUE TITLE
cannot load is-plain-obj with 7.1.0

### ISSUE THREAD

**Issue by JorisM** [axa-group/oauth2-mock-server#286]
After upgrade to 7.1.0 from 7.0.0 we encounter the following error: 

```
2023-10-23 14:18:57 /app/node_modules/oauth2-mock-server/dist/lib/helpers.js:9
2023-10-23 14:18:57 const is_plain_obj_1 = __importDefault(require("is-plain-obj"));
2023-10-23 14:18:57                                        ^
2023-10-23 14:18:57 
2023-10-23 14:18:57 Error [ERR_REQUIRE_ESM]: require() of ES Module /app/node_modules/is-plain-obj/index.js from /app/node_modules/oauth2-mock-server/dist/lib/helpers.js not supported.
2023-10-23 14:18:57 Instead change the require of index.js in /app/node_modules/oauth2-mock-server/dist/lib/helpers.js to a dynamic import() which is available in all CommonJS modules.
2023-10-23 14:18:57     at Object.<anonymous> (/app/node_modules/oauth2-mock-server/dist/lib/helpers.js:9:40)
2023-10-23 14:18:57     at Object.<anonymous> (/app/node_modules/oauth2-mock-server/dist/lib/oauth2-issuer.js:7:19)
2023-10-23 14:18:57     at Object.<anonymous> (/app/node_modules/oauth2-mock-server/dist/index.js:20:23) {
2023-10-23 14:18:57   code: 'ERR_REQUIRE_ESM'
2023-10-23 14:18:57 }
2023-10-23 14:18:57 
2023-10-23 14:18:57 Node.js v20.8.0
```

as shown above, we use node 20.8.0 and `type: "module"` in our package.json

```package.json
{
    "name": "mock-oauth",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "type": "module",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "ISC",
    "volta": {
        "node": "20.8.0"
    },
    "dependencies": {
        "oauth2-mock-server": "7.1.0"
    }
}

```

**Comment by nulltoken** [comment]
@JorisM Hey! Thanks for reporting this.

Could you please v7.1.1 a try and see if this solves the issue?
